const copy={
 'zh-CN':{title:'兼容图片服务',hint:'漫画使用设置中保存的独立图片接口、模型和扩展参数。统一尺寸读取服务配置；逐格尺寸按分镜选择，须由服务商支持。原生种子、采样器、负面参数和参考图不自动应用；启用的参考图会阻止提交。',fees:'费用以图片服务商记录为准',confirm:'使用 {model}（默认尺寸 {size}，逐格尺寸按分镜）生成 {count} 张图片？本次确认覆盖整批，失败停止后续提交，已保存图片保留。费用以服务商为准。'},
 'zh-TW':{title:'相容圖片服務',hint:'漫畫使用設定中儲存的獨立圖片介面、模型與擴充參數。統一尺寸讀取服務設定；逐格尺寸依分鏡選擇，須由服務商支援。原生種子、採樣器、負面參數與參考圖不會自動套用；啟用的參考圖會阻止提交。',fees:'費用以圖片服務商紀錄為準',confirm:'使用 {model}（預設尺寸 {size}，逐格尺寸依分鏡）產生 {count} 張圖片？本次確認涵蓋整批，失敗後停止提交，已儲存圖片保留。費用以服務商為準。'},
 'en-US':{title:'Compatible image service',hint:'Comics use the independent endpoint, model and extensions saved in Settings. Uniform size uses the service configuration; per-panel sizes must be supported by your provider. Native seed, sampler, negatives and references are not applied automatically. Enabled references block submission.',fees:'Charges are determined by your image provider',confirm:'Generate {count} images with {model} (default size {size}; explicit panel sizes override it)? This confirms the whole batch. Stop further submissions on failure and keep saved images. Provider charges apply.'},
 'ja-JP':{title:'互換画像サービス',hint:'漫画は設定に保存した専用エンドポイント、モデル、拡張パラメーターを使用します。統一サイズはサービス設定、コマ別サイズは各コマの指定を使用します。対応サイズは提供元に依存します。原生シード、サンプラー、ネガティブ設定、参照画像は自動適用されません。有効な参照画像があると送信を停止します。',fees:'料金は画像サービス提供元の記録をご確認ください',confirm:'{model}（標準サイズ {size}、コマ別指定があれば優先）で {count} 枚を生成しますか？この確認はバッチ全体に適用されます。失敗時は後続の送信を停止し、保存済み画像を残します。提供元の料金が適用されます。'},
 'ko-KR':{title:'호환 이미지 서비스',hint:'만화는 설정에 저장된 전용 엔드포인트, 모델, 확장 매개변수를 사용합니다. 공통 크기는 서비스 설정을 따르며 컷별 크기는 제공자가 지원해야 합니다. 기본 시드, 샘플러, 네거티브 및 참조 이미지는 자동 적용되지 않습니다. 활성 참조 이미지가 있으면 전송을 중지합니다.',fees:'요금은 이미지 서비스 제공자 기록을 확인하세요',confirm:'{model}(기본 크기 {size}, 컷별 크기 지정 우선)로 {count}장을 생성할까요? 한 번의 확인으로 전체 배치를 승인합니다. 실패하면 다음 전송을 중지하고 저장한 이미지는 유지합니다. 제공자 요금이 적용됩니다.'},
} as const;
export function comicProviderText(language:unknown){return copy[typeof language==='string'&&language in copy?language as keyof typeof copy:'zh-CN'];}
export function compatibleComicConfirmation(language:unknown,values:{model?:string;size?:string;count:number}){return comicProviderText(language).confirm.replace(/\{(model|size|count)\}/g,(_,key:keyof typeof values)=>String(values[key]??'—'));}
