import type { AppLanguage, ResourceDatabaseId, ResourceDatabaseProgressEvent } from "../../types";

const EN = {
  title: "Models & resource libraries", subtitle: "Resource paths and replaceable local completion databases. User images are never treated as cache.", localModel: "Local ONNX tagger model", unavailable: "Not configured (local ONNX tagger is not connected in this version)", dataPath: "Data storage path", loading: "Loading…",
  databases: "Sources & local databases", databaseHint: "A database is replaced only after confirmation; the previous version remains available for rollback.", mergeTitle: "Image data is always merged and is never overwritten with a database.", mergeHint: "Identical content is skipped; same-name files add “(1)”; reference presets, date groups, and history are merged only.",
  source: "Source", pause: "Pause", resume: "Resume download", update: "Update / repair", install: "Download & install", restore: "Restore previous", preparing: "Preparing", prepareDownload: "Preparing download…", reading: "Reading resource status…",
  installed: "Installed · {version} · {size}", invalid: "Database error: {message}", repair: "repair required", downloaded: "Downloaded {size}; ready to resume", notInstalled: "Not installed · download {size}", sourceLine: "Source: {source} · {license}",
  cacheTitle: "Cache maintenance", cacheHint: "Review the three data levels. Cleanup removes only reproducible caches, never databases or user images.", memory: "L1 memory query cache", entries: "{count} entries · {rate}% hit rate", gallery: "L2 gallery disk cache", files: "{count} files · {size}", sqlite: "L3 SQLite resource databases", databaseCount: "{count} databases · {size}", rescan: "Rescan", clear: "Clear reproducible cache", cleared: "Memory query cache and gallery disk cache cleared; resource databases were kept.",
  confirmInstall: "Replace local resource database?", confirmRestore: "Restore the previous database?", confirmBody: "Only the selected local tag/association database is replaced, and a rollback copy is kept. Generated images, references, presets, favorites, and history are never overwritten, renamed, or deleted.", cancel: "Cancel", agreeInstall: "Agree & start", agreeRestore: "Agree & restore",
  tagCatalog: "Base Danbooru tag catalog", tagCatalogDesc: "Complete tags, categories, popularity, and aliases; becomes the primary local completion database after installation.", cooccurrence: "Local related-tag database", cooccurrenceDesc: "About 3.23 million co-occurrence pairs; replaces the small built-in recommendation table after installation.",
  downloading: "Downloading", paused: "Paused", verifying: "Verifying", extracting: "Extracting", installing: "Replacing safely", complete: "Installation complete", error: "Download failed",
} as const;

type Key = keyof typeof EN;

const OVERRIDES: Record<AppLanguage, Partial<Record<Key, string>>> = {
  "en-US": {},
  "zh-CN": {
    title: "模型与资源库", subtitle: "资源路径和可替换的本地补全数据库。不会把用户图片当作缓存删除。", localModel: "本地 ONNX Tagger 模型", unavailable: "未配置（当前版本尚未接入本地 ONNX Tagger）", dataPath: "数据存储路径", loading: "读取中…", databases: "数据源与本地数据库", databaseHint: "数据库只能在你确认后替换；替换前会留下上一版回滚副本。", mergeTitle: "图片数据始终合并，不参与数据库覆盖。", mergeHint: "相同内容跳过；同名不同内容使用“(1)”递增；参考预设、日期分组和历史只合并。", source: "来源", pause: "暂停", resume: "继续下载", update: "更新 / 修复", install: "下载并安装", restore: "恢复上一版", preparing: "正在准备", prepareDownload: "准备下载…", reading: "正在读取资源状态…", installed: "已安装 · {version} · {size}", invalid: "数据库异常：{message}", repair: "需要修复", downloaded: "已下载 {size}，可继续", notInstalled: "未安装 · 下载 {size}", sourceLine: "来源：{source} · {license}", cacheTitle: "缓存维护", cacheHint: "查看三级数据状态；清理只移除可再生成的缓存，不删除数据库或用户图片。", memory: "L1 内存查询缓存", entries: "{count} 条 · 命中率 {rate}%", gallery: "L2 在线画廊磁盘缓存", files: "{count} 个文件 · {size}", sqlite: "L3 SQLite 资源数据库", databaseCount: "{count} 个数据库 · {size}", rescan: "重新扫描", clear: "清理可再生成缓存", cleared: "内存查询缓存和在线画廊磁盘缓存已清理；资源数据库未删除。", confirmInstall: "确认替换本地资源数据库", confirmRestore: "确认恢复上一版数据库", confirmBody: "此操作只替换所选的本地标签/关联数据库，并保留可回滚副本。不会覆盖、重命名或删除任何生成图片、参考图、参考预设、收藏夹或历史记录。", cancel: "取消", agreeInstall: "同意并开始", agreeRestore: "同意恢复", tagCatalog: "基础 Danbooru 标签目录", tagCatalogDesc: "完整标签、类别、热度与别名；安装后作为本地补全主数据库。", cooccurrence: "本地相关标签数据库", cooccurrenceDesc: "约 323 万组共现关系；安装后替代内置小型相关推荐表。", downloading: "正在下载", paused: "已暂停", verifying: "正在校验", extracting: "正在解压", installing: "正在安全替换", complete: "安装完成", error: "下载失败",
  },
  "zh-TW": {
    title: "模型與資源庫", subtitle: "資源路徑與可替換的本機補全資料庫。不會把使用者圖片當作快取刪除。", localModel: "本機 ONNX Tagger 模型", unavailable: "未設定（此版本尚未接入本機 ONNX Tagger）", dataPath: "資料儲存路徑", loading: "讀取中…", databases: "資料來源與本機資料庫", databaseHint: "資料庫只會在你確認後替換，並保留上一版供復原。", mergeTitle: "圖片資料一律合併，不參與資料庫覆蓋。", mergeHint: "相同內容會略過；同名不同內容加上「(1)」；參考預設、日期群組與歷史只合併。", source: "來源", pause: "暫停", resume: "繼續下載", update: "更新／修復", install: "下載並安裝", restore: "還原上一版", preparing: "準備中", prepareDownload: "準備下載…", reading: "正在讀取資源狀態…", installed: "已安裝 · {version} · {size}", invalid: "資料庫異常：{message}", repair: "需要修復", downloaded: "已下載 {size}，可繼續", notInstalled: "未安裝 · 下載 {size}", sourceLine: "來源：{source} · {license}", cacheTitle: "快取維護", cacheHint: "檢視三級資料狀態；清理只移除可重建快取，不會刪除資料庫或使用者圖片。", memory: "L1 記憶體查詢快取", entries: "{count} 筆 · 命中率 {rate}%", gallery: "L2 線上畫廊磁碟快取", files: "{count} 個檔案 · {size}", sqlite: "L3 SQLite 資源資料庫", databaseCount: "{count} 個資料庫 · {size}", rescan: "重新掃描", clear: "清理可重建快取", cleared: "已清理記憶體查詢與線上畫廊磁碟快取；資源資料庫已保留。", confirmInstall: "確認替換本機資源資料庫", confirmRestore: "確認還原上一版資料庫", confirmBody: "只會替換選取的本機標籤／關聯資料庫，並保留復原副本。不會覆蓋、重新命名或刪除生成圖片、參考圖、預設、收藏或歷史。", cancel: "取消", agreeInstall: "同意並開始", agreeRestore: "同意還原", tagCatalog: "基礎 Danbooru 標籤目錄", tagCatalogDesc: "完整標籤、分類、熱度與別名；安裝後作為主要本機補全資料庫。", cooccurrence: "本機相關標籤資料庫", cooccurrenceDesc: "約 323 萬組共現關係；安裝後取代內建的小型推薦表。", downloading: "下載中", paused: "已暫停", verifying: "驗證中", extracting: "解壓縮中", installing: "安全替換中", complete: "安裝完成", error: "下載失敗",
  },
  "ja-JP": {
    title: "モデルとリソース", subtitle: "リソースパスと交換可能なローカル補完 DB。ユーザー画像はキャッシュとして削除しません。", localModel: "ローカル ONNX Tagger モデル", unavailable: "未設定（このバージョンでは未接続）", dataPath: "データ保存先", loading: "読み込み中…", databases: "データソースとローカル DB", databaseHint: "確認後にだけ置換し、前の版をロールバック用に残します。", mergeTitle: "画像データは常にマージされ、DB 置換の対象外です。", mergeHint: "同一内容はスキップし、同名の別内容には「(1)」を付け、プリセット・日付グループ・履歴はマージだけ行います。", source: "ソース", pause: "一時停止", resume: "ダウンロード再開", update: "更新／修復", install: "ダウンロードしてインストール", restore: "前の版に戻す", preparing: "準備中", prepareDownload: "ダウンロード準備中…", reading: "リソース状態を読み込み中…", installed: "インストール済み · {version} · {size}", invalid: "DB エラー：{message}", repair: "修復が必要", downloaded: "{size} ダウンロード済み・再開可能", notInstalled: "未インストール · {size} をダウンロード", sourceLine: "ソース：{source} · {license}", cacheTitle: "キャッシュ管理", cacheHint: "3層の状態を確認します。削除するのは再生成可能なキャッシュだけです。", memory: "L1 メモリ検索キャッシュ", entries: "{count} 件 · ヒット率 {rate}%", gallery: "L2 ギャラリーのディスクキャッシュ", files: "{count} ファイル · {size}", sqlite: "L3 SQLite リソース DB", databaseCount: "{count} DB · {size}", rescan: "再スキャン", clear: "再生成可能キャッシュを消去", cleared: "メモリ検索とギャラリーのキャッシュを消去しました。リソース DB は保持されています。", confirmInstall: "ローカルリソース DB を置換しますか？", confirmRestore: "前の DB を復元しますか？", confirmBody: "選択したタグ／関連 DB だけを置換し、ロールバックコピーを残します。生成画像・参照・プリセット・お気に入り・履歴は変更しません。", cancel: "キャンセル", agreeInstall: "同意して開始", agreeRestore: "同意して復元", tagCatalog: "Danbooru 基本タグカタログ", tagCatalogDesc: "タグ・分類・人気度・別名を収録。インストール後は主要なローカル補完 DB になります。", cooccurrence: "ローカル関連タグ DB", cooccurrenceDesc: "約323万組の共起関係。インストール後は内蔵の小型推薦表を置き換えます。", downloading: "ダウンロード中", paused: "一時停止", verifying: "検証中", extracting: "展開中", installing: "安全に置換中", complete: "インストール完了", error: "ダウンロード失敗",
  },
  "ko-KR": {
    title: "모델 및 리소스 라이브러리", subtitle: "리소스 경로와 교체 가능한 로컬 자동완성 DB입니다. 사용자 이미지는 캐시로 삭제하지 않습니다.", localModel: "로컬 ONNX Tagger 모델", unavailable: "미설정(이 버전에서는 아직 연결되지 않음)", dataPath: "데이터 저장 경로", loading: "불러오는 중…", databases: "데이터 소스 및 로컬 DB", databaseHint: "확인 후에만 교체하며 이전 버전은 복원용으로 보관합니다.", mergeTitle: "이미지 데이터는 항상 병합되며 DB 교체 대상이 아닙니다.", mergeHint: "같은 내용은 건너뛰고, 같은 이름의 다른 파일에는 “(1)”을 붙이며, 프리셋·날짜 그룹·기록은 병합만 합니다.", source: "출처", pause: "일시정지", resume: "다운로드 계속", update: "업데이트/복구", install: "다운로드 및 설치", restore: "이전 버전 복원", preparing: "준비 중", prepareDownload: "다운로드 준비 중…", reading: "리소스 상태 확인 중…", installed: "설치됨 · {version} · {size}", invalid: "DB 오류: {message}", repair: "복구 필요", downloaded: "{size} 다운로드됨, 계속 가능", notInstalled: "미설치 · {size} 다운로드", sourceLine: "출처: {source} · {license}", cacheTitle: "캐시 관리", cacheHint: "3단계 데이터 상태를 확인합니다. 재생성 가능한 캐시만 삭제합니다.", memory: "L1 메모리 검색 캐시", entries: "{count}개 · 적중률 {rate}%", gallery: "L2 갤러리 디스크 캐시", files: "{count}개 파일 · {size}", sqlite: "L3 SQLite 리소스 DB", databaseCount: "{count}개 DB · {size}", rescan: "다시 스캔", clear: "재생성 가능 캐시 삭제", cleared: "메모리 검색 및 갤러리 디스크 캐시를 삭제했습니다. 리소스 DB는 유지됩니다.", confirmInstall: "로컬 리소스 DB를 교체할까요?", confirmRestore: "이전 DB를 복원할까요?", confirmBody: "선택한 태그/연관 DB만 교체하고 복원 사본을 보관합니다. 생성 이미지, 참조, 프리셋, 즐겨찾기, 기록은 변경하지 않습니다.", cancel: "취소", agreeInstall: "동의하고 시작", agreeRestore: "동의하고 복원", tagCatalog: "Danbooru 기본 태그 카탈로그", tagCatalogDesc: "태그, 분류, 인기, 별칭을 포함하며 설치 후 기본 로컬 자동완성 DB가 됩니다.", cooccurrence: "로컬 관련 태그 DB", cooccurrenceDesc: "약 323만 개 공기 관계를 포함하며 설치 후 내장 소형 추천표를 대체합니다.", downloading: "다운로드 중", paused: "일시정지됨", verifying: "검증 중", extracting: "압축 해제 중", installing: "안전하게 교체 중", complete: "설치 완료", error: "다운로드 실패",
  },
};

export function resourceText(language: AppLanguage, key: Key, values: Record<string, unknown> = {}) {
  const template = OVERRIDES[language][key] ?? EN[key];
  return Object.entries(values).reduce((result, [name, value]) => result.replaceAll(`{${name}}`, String(value)), template);
}

export function resourcePhaseText(language: AppLanguage, phase: ResourceDatabaseProgressEvent["phase"]) {
  return resourceText(language, phase);
}

export function resourceDefinitionText(language: AppLanguage, id: ResourceDatabaseId) {
  return id === "tagCatalog"
    ? { label: resourceText(language, "tagCatalog"), description: resourceText(language, "tagCatalogDesc") }
    : { label: resourceText(language, "cooccurrence"), description: resourceText(language, "cooccurrenceDesc") };
}
