// Derived from Langbai electron/ipc/store.ts defaultSettings; MIT (c) 2026 Langbai.
// Output directory comes from the Rust host; no Electron runtime is included.
import type { AppSettings } from "../langbai/src/types";
import { normalizeCompletionSound } from "../langbai/src/completion-sound";
import { createDefaultImageTaskPromptPreset } from "../langbai/src/tavern/image-task-preset";
import { DEFAULT_AGENT_COMPACT_THRESHOLD } from "../langbai/src/agent/context";
import { DEFAULT_AGENT_PROVIDER_PRESET } from "../langbai/src/agent/provider-catalog";
function emptyModeTemplates(): AppSettings["reversePromptTemplates"] {
  return { tags: "", natural: "", mixed: "" };
}
export function defaultSettings(outputDir: string = ""): AppSettings {
  return {
    hasOnboarded: false,
    language: "zh-CN",
    outputDir: outputDir,
    onlineGalleryDownloadDir: "",
    logDir: "",
    apiBaseUrl: "https://api.novelai.net",
    imageBaseUrl: "https://image.novelai.net",
    imageProvider: "novelai",
    imageApiKey: "",
    compatibleImage: { baseUrl: "", model: "", size: "1024x1024", responseFormat: "auto" },
    harnessAutoUpdatePlugins: true,
    allowCustomEndpoint: true,
    allowCustomEndpointFallback: false,
    proxyMode: "auto",
    proxyUrl: "",
    proxyForNai: true,
    proxyForMcp: true,
    proxyForAi: true,
    proxyForUpdate: true,
    proxyForTranslate: true,
    updateSource: "github",
    theme: "light",
    reduceMotion: false,
    completionSound: normalizeCompletionSound(null),
    autoComplete: true,
    weightHighlight: true,
    promptRandomizer: true,
    superDrop: true,
    streamPreviewEnabled: true,
    showFloatingToolbar: true,
    historyJumpAfterGenerate: true,
    historyRetentionDays: 30,
    loggingEnabled: true,
    keepImageMetadata: true,
    autoBackupEnabled: true,
    autoBackupIntervalHours: 24,
    autoBackupRetentionCount: 7,
    autoBackupIncludeImages: false,
    autoBackupAssetPolicyVersion: 1,
    backupDir: "",
    visionApiUrl: "https://api.openai.com/v1",
    visionApiKey: "",
    visionApiModel: "gpt-4o",
    visionSystemPrompt: "",
    reversePromptMode: "tags" as const,
    reversePromptTemplateVersion: "v5" as const,
    reversePromptTemplates: emptyModeTemplates(),
    reversePromptTemplatesV45: emptyModeTemplates(),
    reverseConvertDshEnabled: true,
    reverseConvertDshMode: "focused" as const,
    reverseConvertPromptPresets: [createDefaultImageTaskPromptPreset()],
    reverseConvertPromptPresetId: createDefaultImageTaskPromptPreset().id,
    comicAnalyzePromptTemplates: { tags: "", natural: "", mixed: "" },
    comicAnalyzePromptTemplate: "",
    promptOptimizeTemplate: "",
    promptAssistantTemplate: "",
    convertApiUrl: "https://api.openai.com/v1",
    convertApiKey: "",
    convertApiModel: "gpt-4o-mini",
    convertSystemPrompt: "",
    agentApiProtocol: DEFAULT_AGENT_PROVIDER_PRESET.protocol,
    agentApiBaseUrl: DEFAULT_AGENT_PROVIDER_PRESET.baseUrl,
    agentApiKey: "",
    agentApiModel: DEFAULT_AGENT_PROVIDER_PRESET.model,
    agentProviderName: DEFAULT_AGENT_PROVIDER_PRESET.providerName,
    agentContextWindow: DEFAULT_AGENT_PROVIDER_PRESET.contextWindow,
    agentMaxOutputTokens: DEFAULT_AGENT_PROVIDER_PRESET.maxOutputTokens,
    agentAutoCompact: true,
    agentAutoCompactThreshold: DEFAULT_AGENT_COMPACT_THRESHOLD,
    agentVisionEnabled: true,
    convertMode: "tags" as const,
    convertPromptTemplateVersion: "v5" as const,
    convertPromptTemplates: { tags: "", natural: "", mixed: "" },
    convertPromptTemplatesV45: { tags: "", natural: "", mixed: "" },
    tagServerEnabled: false,
    tagServerUrl: "",
    tagServerApiKey: "",
    tagServerType: "rest" as const,
    tagServerCommand: "",
    tagServerArgs: "",
    tagServerTool: "search_tags",
    mcpForCapsule: true,
    mcpForReverse: false,
    mcpForConvert: false,
    translateProvider: "google" as const,
    baiduAppId: "",
    baiduSecret: "",
    translateAiApiUrl: "https://api.openai.com/v1",
    translateAiApiKey: "",
    translateAiModel: "gpt-4o-mini",
    activeHistoryGroupId: "",
    generationGroupId: "",
    modelMode: "anime" as const,
    lockStylePrompt: false,
    lockNegativePrompt: false,
    savedStylePrompt: "",
    savedNegativePrompt: "",
    imageNameTemplate: "{date}_{seq}_{model}",
    promptTemplates: [],
    stylePromptPresets: [],
    stylePromptPresetGroups: ["Default"],
    positivePromptPresets: [],
    promptChunks: [],
    lastGenerationState: null,
    persistGenerateParams: true,
    persistI2IParams: true,
    persistInpaintParams: true,
    persistUpscaleParams: true,
    persistDirectorParams: true,
  };
}
