import type {PromptDocument,PromptBlock} from "../platform/types";
import {compilePrompt,compileLayers} from "./prompt";
export default function PromptEditor({doc,onChange,disabled=false}:{doc:PromptDocument;onChange:(doc:PromptDocument)=>void;disabled?:boolean}) {
  function edit(id:string,patch:Partial<PromptBlock>){onChange({...doc,blocks:doc.blocks.map(b=>b.id===id?{...b,...patch}:b)});}
  function move(index:number,delta:number){const blocks=[...doc.blocks];const next=index+delta;if(next<0||next>=blocks.length)return;[blocks[index],blocks[next]]=[blocks[next],blocks[index]];onChange({...doc,blocks});}
  return <section className="panel prompt-editor"><div className="panel-heading"><h2>提示词</h2><span className="chip">{compilePrompt(doc).length} 字符 · 非 Token 数</span></div>
    <div className="segmented" aria-label="提示词编辑模式"><button className={doc.mode==="raw"?"selected":""} disabled={disabled} onClick={()=>onChange({...doc,mode:"raw"})}>原文编辑</button><button className={doc.mode==="layered"?"selected":""} disabled={disabled} onClick={()=>onChange({...doc,mode:"layered"})}>分层编辑</button></div>
    <p className="hint">分层是可调整的应用模板，不是 NAI 官方排序。切换保留两份内容；不去重、不改写权重。</p>
    {doc.mode==="raw"?<><label htmlFor="prompt">正向提示词</label><textarea id="prompt" className="raw-prompt" value={doc.raw} disabled={disabled} onChange={e=>onChange({...doc,raw:e.target.value})} placeholder="写下你的画面。重复标签、权重语法与原文顺序保持不变。" spellCheck={false}/></>:<div className="prompt-blocks">{doc.blocks.map((b,index)=><details className={b.enabled?"prompt-block":"prompt-block off"} key={b.id} open={b.text!==""||index<2}><summary><input aria-label={`启用${b.title}`} type="checkbox" checked={b.enabled} disabled={disabled} onClick={e=>e.stopPropagation()} onChange={e=>edit(b.id,{enabled:e.target.checked})}/><span>{b.title}</span><small>{b.text.length||"空"}</small></summary><div className="block-body"><div className="block-tools"><button type="button" aria-label={`上移${b.title}`} disabled={disabled||index===0} onClick={()=>move(index,-1)}>↑ 上移</button><button type="button" aria-label={`下移${b.title}`} disabled={disabled||index===doc.blocks.length-1} onClick={()=>move(index,1)}>↓ 下移</button></div><textarea aria-label={b.title} value={b.text} disabled={disabled} onChange={e=>edit(b.id,{text:e.target.value})} spellCheck={false}/></div></details>)}</div>}
    <details className="prompt-preview"><summary>查看实际提交的正向提示词</summary><pre data-testid="compiled-prompt">{compilePrompt(doc)||"（空）"}</pre></details>
    {doc.mode==="layered"&&<button className="text-button" disabled={disabled} onClick={()=>{if(doc.raw&&!window.confirm("这会替换原文编辑中的内容；分层仍会保留。确认替换？"))return;onChange({...doc,raw:compileLayers(doc),mode:"raw"});}}>用分层预览替换原文</button>}
  </section>;
}
