const cn={units:'单元',natural:'自然语言',undo:'撤销',redo:'重做',optimize:'提示词优化',custom:'自定义提示词助手',more:'更多工具',current:'当前提示词',empty:'（当前提示词为空）',instruction:'你的修改要求',hint:'例如：改为雨夜街道，让动作更有张力；保留角色和服装。',run:'生成预览',busy:'正在生成预览…',preview:'结果预览',apply:'应用到提示词',cancel:'取消',stale:'当前提示词或模板已改变，请重新生成预览后再应用。',failed:'生成失败，请检查转换服务配置后重试。',template:'沿用转换模板',notice:'先预览再应用；不改动风格和负面提示词，不会开始生图。',retry:'重新生成',modes:['标签','自然语言','混合']};
type Text=typeof cn;
const en:Text={units:'units',natural:'Natural',undo:'Undo',redo:'Redo',optimize:'Optimize prompt',custom:'Custom prompt assistant',more:'More tools',current:'Current prompt',empty:'(Empty prompt)',instruction:'Requested changes',hint:'For example: a rainy night street and a more dynamic pose; keep the character and clothing.',run:'Generate preview',busy:'Generating preview…',preview:'Result preview',apply:'Apply to prompt',cancel:'Cancel',stale:'The prompt or template has changed. Generate a new preview before applying.',failed:'Request failed. Check the conversion service and retry.',template:'Conversion template',notice:'Preview before applying. Style and negative prompts stay unchanged. No image will be generated.',retry:'Generate again',modes:['Tags','Natural','Mixed']};
const texts:Record<string,Text>={
 'zh-CN':cn,'en-US':en,
 'zh-TW':{...cn,units:'單元',natural:'自然語言',undo:'復原',redo:'重做',optimize:'提示詞最佳化',custom:'自訂提示詞助手',current:'目前提示詞',empty:'（目前提示詞為空）',instruction:'你的修改需求',hint:'例如：改為雨夜街道，讓動作更有張力；保留角色和服裝。',run:'產生預覽',busy:'正在產生預覽…',preview:'結果預覽',apply:'套用至提示詞',stale:'目前提示詞或範本已改變，請重新產生預覽。',failed:'產生失敗，請檢查轉換服務設定後重試。',template:'沿用轉換範本',notice:'先預覽再套用；不改動風格和負面提示詞，不會開始生圖。',retry:'重新產生',modes:['標籤','自然語言','混合']},
 'ja-JP':{...en,units:'単位',natural:'自然言語',undo:'元に戻す',redo:'やり直す',optimize:'プロンプトを最適化',custom:'カスタムプロンプト助手',more:'その他のツール',current:'現在のプロンプト',empty:'（空のプロンプト）',instruction:'変更内容',hint:'例：雨の夜道に変更し、ポーズを強調。キャラクターと服装は維持。',run:'プレビューを生成',busy:'生成中…',preview:'結果プレビュー',apply:'プロンプトに適用',cancel:'キャンセル',stale:'プロンプトまたはテンプレートが変更されました。再生成してください。',failed:'失敗しました。変換サービスの設定を確認してください。',template:'変換テンプレート',notice:'確認後に適用します。画風・ネガティブは変更せず、画像も生成しません。',retry:'再生成',modes:['タグ','自然言語','混合']},
 'ko-KR':{...en,units:'단위',natural:'자연어',undo:'실행 취소',redo:'다시 실행',optimize:'프롬프트 최적화',custom:'사용자 지정 프롬프트 도우미',more:'추가 도구',current:'현재 프롬프트',empty:'(빈 프롬프트)',instruction:'수정 요청',hint:'예: 비 오는 밤거리로 변경하고 동작을 강조. 캐릭터와 의상은 유지.',run:'미리보기 생성',busy:'생성 중…',preview:'결과 미리보기',apply:'프롬프트에 적용',cancel:'취소',stale:'프롬프트 또는 템플릿이 변경되었습니다. 다시 생성하세요.',failed:'실패했습니다. 변환 서비스 설정을 확인하세요.',template:'변환 템플릿',notice:'미리보기 후 적용합니다. 스타일과 부정 프롬프트를 유지하며 이미지를 생성하지 않습니다.',retry:'다시 생성',modes:['태그','자연어','혼합']},
};
export function promptEditorText(language:unknown){return texts[String(language)]??en;}
