import {FilePicker} from './components/FilePicker';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import labels from '../shared/style-library-ui.json';
import {useAppStore} from './store';
import {STYLE_SORTS,sortStyles,moveStyle,parseStyleLines,matchStyleImages,styleCoverIndex} from './style-library';
import {changeStyles,countStyleUse,setStyleSort,saveGalleryStyle} from './style-library-client';
import type {StylePromptPreset} from './types';
import {Button,SelectMenuCompat as Select} from './components/ui';
import {Icon} from './components/icons';
import {PreviewImageViewer} from './components/PreviewImageViewer';
export const styleText=(language:unknown)=>labels[language as keyof typeof labels]??labels['en-US'];
export function StyleSortSelect(){const s=useAppStore(x=>x.settings),t=styleText(s?.language);return <label>{t.sort}<Select aria-label={t.sort} value={s?.stylePromptPresetSort??'default'} onChange={e=>void setStyleSort(e.target.value).catch(e=>useAppStore.getState().setToast(String(e)))}>{STYLE_SORTS.map(v=><option key={v} value={v}>{v==='name'?t.nameSort:t[v]}</option>)}</Select></label>;}
export function GallerySaveStyleButton({name,prompt,images}:{name:string;prompt:string;images:string[]}) {
 const t=styleText(useAppStore(s=>s.settings?.language));const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><Button disabled={busy||!prompt.trim()} onClick={async()=>{setBusy(true);setError('');try{await saveGalleryStyle(name,prompt,images);useAppStore.getState().setToast(t.saved);}catch(e){setError(String(e));}finally{setBusy(false);}}}>{busy?'…':t.saveStyle}</Button>{error&&<span role="alert">{error}</span>}</>;
}
export default function StyleLibrary(){
 const settings=useAppStore(s=>s.settings),t=styleText(settings?.language),items=settings?.stylePromptPresets??[];
 const [query,setQuery]=useState(''),[group,setGroup]=useState(''),[draft,setDraft]=useState<StylePromptPreset|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [batch,setBatch]=useState(false),[lines,setLines]=useState(''),[files,setFiles]=useState<File[]>([]),[match,setMatch]=useState('none');
 const [drag,setDrag]=useState(''),[over,setOver]=useState(''),[preview,setPreview]=useState<{preset:StylePromptPreset;index:number}|null>(null),[groupName,setGroupName]=useState('');
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setPreview(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 const libraryRef=useRef<HTMLElement>(null);
 const [ratingText,setRatingText]=useState('0');
 const rating=Number(ratingText),ratingValid=ratingText.trim()!==''&&Number.isFinite(rating)&&rating>=0&&rating<=5;
 const edit=(p:StylePromptPreset)=>{setRatingText(String(p.rating??0));setError('');setDraft({...p,previewImages:[...p.previewImages??[]]});};
 // Scroll this panel only: scrollIntoView also scrolls the hidden app-shell ancestor.
 useLayoutEffect(()=>{if(draft&&libraryRef.current)libraryRef.current.scrollTop=0;},[draft?.id]);
 const groups=[...new Set(['Default',...(settings?.stylePromptPresetGroups??[]),...items.map(p=>p.group)])];
 const visible=sortStyles(items,settings?.stylePromptPresetSort).filter(p=>(!group||p.group===group)&&`${p.name}\n${p.prompt}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 async function run(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const fresh=(name='',prompt=''):StylePromptPreset=>({id:crypto.randomUUID(),name,prompt,group:group||'Default',createdAt:new Date().toISOString(),rating:0,usageCount:0,previewImages:[]});
 async function cancel(){if(draft){const original=items.find(p=>p.id===draft.id);for(const im of draft.previewImages??[])if(!original?.previewImages?.some(x=>x.id===im.id))await window.naiDesktop.deleteStylePromptPresetImage(draft.id,im.id);}setDraft(null);setBatch(false);}
 async function apply(p:StylePromptPreset){await countStyleUse(p.id);useAppStore.getState().setParam('stylePrompt',p.prompt);useAppStore.getState().setActiveTab('generate');}
 async function reorder(id:string,target:string){await changeStyles(all=>moveStyle(all,id,target,visible.map(p=>p.id)));await setStyleSort('custom');}
 async function save(){if(!draft?.name.trim()||!draft.prompt.trim()||!ratingValid)return;const value={...draft,coverImageId:draft.previewImages?.[styleCoverIndex(draft)]?.id,rating,name:draft.name.trim(),prompt:draft.prompt.trim()};const old=items.find(x=>x.id===value.id);
  await changeStyles(all=>all.some(p=>p.id===value.id)?all.map(p=>p.id===value.id?{...p,...value,usageCount:p.usageCount,sortOrder:p.sortOrder}:p):[...all,value]);
  for(const im of old?.previewImages??[])if(!value.previewImages?.some(x=>x.id===im.id))await window.naiDesktop.deleteStylePromptPresetImage(value.id,im.id);
  setDraft(null);useAppStore.getState().setToast(t.saved);
 }
 async function importBatch(){const rows=parseStyleLines(lines);if(!rows.length)return;const matches=matchStyleImages(files.map(f=>f.name),rows,match),created:StylePromptPreset[]=[];let committed=false;
  try{for(const [i,row] of rows.entries()){const p=fresh(row.name,row.prompt);created.push(p);const paths=matches[i].map(n=>window.naiDesktop.getPathForFile(files.find(f=>f.name===n)!));if(paths.length){p.previewImages=await window.naiDesktop.importStylePromptPresetImagePaths(paths,p.id,9);if(p.previewImages.length!==paths.length)throw Error(`${row.name}: ${t.images}`);}}
   await changeStyles(all=>[...all,...created]);committed=true;setBatch(false);setLines('');setFiles([]);useAppStore.getState().setToast(`${t.saved} · ${created.length}`);
  }finally{if(!committed)await Promise.allSettled(created.map(p=>window.naiDesktop.deleteStylePromptPresetImages(p.id)));}
 }
 return <main ref={libraryRef} className="style-library">{!draft&&<><header className="style-library-heading"><div><h2>{t.title}</h2><span>{items.length}</span></div><Button disabled={busy||!!draft||batch} onClick={()=>edit(fresh())}><Icon name="plus"/>{t.new}</Button><Button disabled={busy||!!draft||batch} onClick={()=>setBatch(true)}>{t.batch}</Button></header>
 <div className="style-library-filters"><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/><Select aria-label={t.group} value={group} onChange={e=>setGroup(e.target.value)}><option value="">{t.all}</option>{groups.map(g=><option key={g}>{g}</option>)}</Select><StyleSortSelect/></div>
 <div className="style-library-groups"><input aria-label={t.newGroup} placeholder={t.newGroup} value={groupName} onChange={e=>setGroupName(e.target.value)}/><Button disabled={busy||!groupName.trim()||groups.includes(groupName.trim())} onClick={()=>void run(async()=>{await window.naiDesktop.setSetting('stylePromptPresetGroups',[...groups,groupName.trim()]);await useAppStore.getState().refreshSettings();setGroup(groupName.trim());setGroupName('');})}>{t.newGroup}</Button><Button disabled={busy||!group||group==='Default'} onClick={()=>void run(async()=>{await changeStyles(all=>all.map(p=>p.group===group?{...p,group:'Default'}:p));await window.naiDesktop.setSetting('stylePromptPresetGroups',groups.filter(g=>g!==group));await useAppStore.getState().refreshSettings();setGroup('');})}>{t.deleteGroup}</Button></div></>}
 {error&&<p role="alert">{error}</p>}
 {draft&&<section className="style-library-editor" aria-label={t.edit}><h3>{draft.name||t.new}</h3><label>{t.name}<input value={draft.name} maxLength={120} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{t.prompt}<textarea aria-label={t.prompt} rows={6} value={draft.prompt} onChange={e=>setDraft({...draft,prompt:e.target.value})}/></label><div className="style-library-filters"><label>{t.group}<Select value={draft.group} onChange={e=>setDraft({...draft,group:e.target.value})}>{groups.map(g=><option key={g}>{g}</option>)}</Select></label><label>{t.rating}<input aria-label={t.rating} type="number" min="0" max="5" step="any" inputMode="decimal" value={ratingText} aria-invalid={!ratingValid} aria-describedby={!ratingValid?'style-rating-error':undefined} onChange={e=>setRatingText(e.target.value)}/>{!ratingValid&&<small id="style-rating-error" role="alert">{t.ratingRange}</small>}</label></div>
 <div className="style-library-previews">{draft.previewImages?.map((im,i)=><div key={im.id}><button onClick={()=>setPreview({preset:draft,index:i})}><img src={im.fileUrl} alt={im.name}/></button><Button disabled={busy} aria-pressed={styleCoverIndex(draft)===i} onClick={()=>setDraft({...draft,coverImageId:im.id})}>{styleCoverIndex(draft)===i?t.cover:t.setCover}</Button><Button disabled={busy} onClick={()=>{if(!window.confirm(`${t.confirmImageDelete}\n${im.name}`))return;void run(async()=>{if(!items.find(p=>p.id===draft.id)?.previewImages?.some(x=>x.id===im.id))await window.naiDesktop.deleteStylePromptPresetImage(draft.id,im.id);setDraft({...draft,previewImages:draft.previewImages!.filter(x=>x.id!==im.id)});});}}>{t.delete}</Button></div>)}</div>
 <Button disabled={busy||(draft.previewImages?.length??0)>=9} onClick={()=>void run(async()=>{const added=await window.naiDesktop.importStylePromptPresetImages(draft.id,9-(draft.previewImages?.length??0),t.addImages);setDraft({...draft,previewImages:[...(draft.previewImages??[]),...added]});})}>{t.addImages} · {draft.previewImages?.length??0}/9</Button><footer><Button disabled={busy} onClick={()=>void run(cancel)}>{t.cancel}</Button><Button variant="primary" disabled={busy||!draft.name.trim()||!draft.prompt.trim()||!ratingValid} onClick={()=>void run(save)}>{t.save}</Button></footer></section>}
 {batch&&<section className="style-library-editor" aria-label={t.batch}><h3>{t.batch}</h3><label>{t.lines}<textarea rows={7} value={lines} onChange={e=>setLines(e.target.value)}/></label><label>{t.match}<Select value={match} onChange={e=>setMatch(e.target.value)}><option value="none">{t.none}</option><option value="order">{t.byOrder}</option><option value="name">{t.byName}</option></Select></label><label>{t.selectImages}<FilePicker  accept="image/png,image/jpeg,image/webp" multiple onChange={e=>setFiles([...e.target.files??[]])}/></label><p>{files.map(f=>f.name).join(', ')}</p><footer><Button disabled={busy} onClick={()=>setBatch(false)}>{t.cancel}</Button><Button variant="primary" disabled={busy||!parseStyleLines(lines).length} onClick={()=>void run(importBatch)}>{t.import} · {parseStyleLines(lines).length}</Button></footer></section>}
 {!draft&&!batch&&<div className="style-library-list">{visible.length===0&&<p>{t.empty}</p>}{visible.map((p,i)=><article key={p.id} className={`style-library-card ${drag===p.id?'is-dragging':''} ${over===p.id?'is-drop-target':''}`} onDragOver={e=>{if(drag){e.preventDefault();setOver(p.id);}}} onDrop={e=>{e.preventDefault();if(drag)void run(()=>reorder(drag,p.id));setDrag('');setOver('');}}>
 <button className="style-library-handle" aria-label={`${t.drag}: ${p.name}`} draggable={!busy} onDragStart={e=>{setDrag(p.id);e.dataTransfer.setData('text/plain',p.id);e.dataTransfer.effectAllowed='move';e.dataTransfer.setDragImage(e.currentTarget.parentElement!,20,20);}} onDragEnd={()=>{setDrag('');setOver('');}}><span aria-hidden="true">≡</span></button>
 <div className="style-library-preview-group" role="group" aria-label={`${t.images}: ${p.name}`}><div className="style-library-preview-grid">{p.previewImages?.length?<button aria-label={`${t.images}: ${p.name} · ${styleCoverIndex(p)+1}/${p.previewImages.length}`} onClick={()=>setPreview({preset:p,index:styleCoverIndex(p)})}><img src={p.previewImages[styleCoverIndex(p)].fileUrl} alt={p.previewImages[styleCoverIndex(p)].name} loading="lazy"/></button>:<span className="style-library-empty-preview"><Icon name="images"/></span>}</div>{!!p.previewImages?.length&&<small>{t.images} · {p.previewImages.length}</small>}</div><div className="style-library-info"><h3>{p.name}</h3><small>{p.group} · {t.rating} {p.rating??0}/5 · {t.uses} {p.usageCount??0}</small><p>{p.prompt}</p></div>
 <div className="style-library-actions"><Button disabled={busy} onClick={()=>edit(p)}>{t.edit}</Button><Button disabled={busy} onClick={()=>void run(()=>apply(p))}>{t.apply}</Button><Button aria-label={`${t.moveUp}: ${p.name}`} disabled={busy||i===0} onClick={()=>void run(()=>reorder(p.id,visible[i-1].id))}>↑</Button><Button aria-label={`${t.moveDown}: ${p.name}`} disabled={busy||i===visible.length-1} onClick={()=>void run(()=>reorder(p.id,visible[i+1].id))}>↓</Button><Button variant="danger" disabled={busy} onClick={()=>{if(window.confirm(t.confirmDelete))void run(async()=>{await changeStyles(all=>all.filter(x=>x.id!==p.id));await window.naiDesktop.deleteStylePromptPresetImages(p.id);});}}>{t.delete}</Button></div></article>)}</div>}
 {preview&&<div className="style-image-lightbox" role="dialog" aria-modal="true" onClick={e=>{if(e.target===e.currentTarget)setPreview(null);}}><button aria-label={t.close} onClick={()=>setPreview(null)}>×</button><PreviewImageViewer images={preview.preset.previewImages!.map(im=>({src:im.fileUrl,alt:im.name}))} index={preview.index} onIndex={index=>setPreview({...preview,index})} onBackgroundClick={()=>setPreview(null)}/></div>}
 </main>;
}
