const en = {
 title:'Works library', subtitle:'Browse saved originals without changing your generation settings', search:'Search filename, recorded prompt or seed', refresh:'Refresh', all:'All works', groups:'Groups', ungrouped:'Ungrouped', folders:'Recorded folders', dates:'All dates', newest:'Newest first', oldest:'Oldest first', loading:'Loading…', empty:'No saved works yet', noMatch:'No matching works', choose:'Select an image to inspect the original', previous:'Previous', next:'Next', selectPage:'Select page', selectAll:'Select filtered', clear:'Clear selection', selected:'Selected', open:'Show in folder', copy:'Copy positive prompt', copyNegative:'Copy negative prompt', original:'Original image metadata', record:'No embedded prompt: showing generation record', copied:'Copied', prompt:'Prompt', negative:'Negative prompt', error:'Operation failed', reset:'Reset filters', count:'works', preview:'Large preview', missing:'Preview unavailable', folderNote:'Folders referenced by saved history; original files stay in place.', favorites:'Open favorites', page:'Page', details:'Image details', read:'Read original prompt', readError:'Original file could not be read. Check its folder, then retry.', retry:'Retry', unavailable:'Desktop history service is unavailable',
};
type Text = typeof en;
const zh:Text = {title:'作品管理',subtitle:'浏览历史原图，不改变当前生成参数',search:'搜索文件名、历史提示词或种子',refresh:'刷新',all:'全部作品',groups:'分组',ungrouped:'未分组',folders:'历史文件夹',dates:'全部日期',newest:'最新在前',oldest:'最早在前',loading:'读取中…',empty:'还没有保存的作品',noMatch:'没有符合条件的作品',choose:'点击一张图片，在这里查看原图',previous:'上一页',next:'下一页',selectPage:'选择本页',selectAll:'选择筛选结果',clear:'取消选择',selected:'已选',open:'打开所在文件夹',copy:'复制正面提示词',copyNegative:'复制负面提示词',original:'原图内嵌提示词',record:'原图未含提示词：以下为历史生成记录',copied:'已复制',prompt:'提示词',negative:'负面提示词',error:'操作失败',reset:'重置筛选',count:'张作品',preview:'大图预览',missing:'预览不可用',folderNote:'这里只列出历史记录涉及的文件夹，不移动原图。',favorites:'打开收藏夹',page:'页',details:'图片信息',read:'读取原图提示词',readError:'原图读取失败，请检查文件目录后重试。',retry:'重试',unavailable:'桌面历史服务尚未就绪'};
const tw:Text = {...zh,title:'作品管理',subtitle:'瀏覽歷史原圖，不改變目前生成參數',search:'搜尋檔名、歷史提示詞或種子',refresh:'重新整理',groups:'分組',ungrouped:'未分組',folders:'歷史資料夾',dates:'全部日期',newest:'最新在前',oldest:'最早在前',loading:'讀取中…',empty:'尚未儲存作品',noMatch:'沒有符合條件的作品',choose:'點選圖片以檢視原圖',previous:'上一頁',next:'下一頁',selectPage:'選擇本頁',selectAll:'選擇篩選結果',clear:'取消選擇',selected:'已選',open:'開啟所在資料夾',copy:'複製正面提示詞',copyNegative:'複製負面提示詞',original:'原圖內嵌提示詞',record:'原圖未含提示詞：以下為歷史生成記錄',copied:'已複製',prompt:'提示詞',negative:'負面提示詞',error:'操作失敗',reset:'重設篩選',preview:'大圖預覽',missing:'預覽無法使用',folderNote:'僅列出歷史記錄涉及的資料夾，不移動原圖。',favorites:'開啟收藏夾',details:'圖片資訊',read:'讀取原圖提示詞',readError:'原圖讀取失敗，請檢查檔案目錄後重試。',retry:'重試',unavailable:'桌面歷史服務尚未就緒'};
const ja:Text = {...en,title:'作品ライブラリ',subtitle:'生成設定を変更せずに保存した原画像を閲覧',search:'ファイル名・記録されたプロンプト・シードを検索',refresh:'更新',all:'すべての作品',groups:'グループ',ungrouped:'未分類',folders:'履歴フォルダー',dates:'すべての日付',newest:'新しい順',oldest:'古い順',loading:'読み込み中…',empty:'保存した作品はありません',noMatch:'一致する作品はありません',choose:'画像を選択して原画像を表示',previous:'前へ',next:'次へ',selectPage:'このページを選択',selectAll:'検索結果を選択',clear:'選択解除',selected:'選択済み',open:'保存先を開く',copy:'正のプロンプトをコピー',copyNegative:'負のプロンプトをコピー',original:'原画像のメタデータ',record:'埋め込みプロンプトなし：生成履歴を表示',copied:'コピーしました',prompt:'プロンプト',negative:'負のプロンプト',error:'操作に失敗しました',reset:'絞り込みを解除',count:'作品',preview:'大きなプレビュー',missing:'プレビューを表示できません',folderNote:'履歴に記録されたフォルダーのみ。原画像は移動しません。',favorites:'お気に入りを開く',page:'ページ',details:'画像情報',read:'原画像のプロンプトを読む',readError:'原画像を読み込めません。保存先を確認して再試行してください。',retry:'再試行',unavailable:'デスクトップ履歴サービスが利用できません'};
const ko:Text = {...en,title:'작품 관리',subtitle:'생성 설정을 변경하지 않고 저장된 원본 보기',search:'파일명, 기록된 프롬프트 또는 시드 검색',refresh:'새로 고침',all:'전체 작품',groups:'그룹',ungrouped:'미분류',folders:'기록된 폴더',dates:'전체 날짜',newest:'최신순',oldest:'오래된순',loading:'불러오는 중…',empty:'저장된 작품이 없습니다',noMatch:'일치하는 작품이 없습니다',choose:'이미지를 선택하여 원본 보기',previous:'이전',next:'다음',selectPage:'현재 페이지 선택',selectAll:'검색 결과 선택',clear:'선택 해제',selected:'선택됨',open:'저장 폴더 열기',copy:'양성 프롬프트 복사',copyNegative:'음성 프롬프트 복사',original:'원본 이미지 메타데이터',record:'내장 프롬프트 없음: 생성 기록 표시',copied:'복사됨',prompt:'프롬프트',negative:'음성 프롬프트',error:'작업 실패',reset:'필터 초기화',count:'작품',preview:'큰 미리보기',missing:'미리보기 없음',folderNote:'기록된 폴더만 표시합니다. 원본 파일은 이동하지 않습니다.',favorites:'즐겨찾기 열기',page:'페이지',details:'이미지 정보',read:'원본 프롬프트 읽기',readError:'원본을 읽지 못했습니다. 폴더를 확인하고 다시 시도하세요.',retry:'재시도',unavailable:'데스크톱 기록 서비스를 사용할 수 없습니다'};
export function worksText(language:unknown):Text { return ({'zh-CN':zh,'zh-TW':tw,'en-US':en,'ja-JP':ja,'ko-KR':ko} as Record<string,Text>)[String(language)] ?? en; }
